issuesOpened: >
  <img src="https://media.tenor.com/images/a44d0c84e5e535a649b16011b8d3c54c/tenor.gif" height=200 />
  <br />
  Thank you for raising a issue. We will try and get back to you as soon as possible.
  <br />
  Please make sure you have given us as much context as possible.
  <br />
  Best,
  <br />
  @terrastories-stewards

pullRequestOpened: >
  <img src="https://media.giphy.com/media/LPx5F48jqLHd9ClF0L/giphy.gif" height=200 />
  <br />
  Thank you for your pull request!
  <br />
  Please make sure you have followed our contributing guidelines. We will review it as soon as possible. 
  <br />
  Best,
  <br />
  @terrastories-stewards