version: '3.2'
services:
  web:
    image: ${DOCKER_IMAGE_NAME-terrastories}
    build:
      context: .
      args:
        precompileassets: "not"
    environment:
      - SECRET_KEY_BASE=456
    env_file:
      - .env
    ports:
      - 3000:3000
      - 3035:3035
    volumes:
      - .:/app:cached
      - type: tmpfs
        target: /app/tmp/pids/
    command: "bundle exec foreman start -f Procfile.development"
