# This app can be run with multiple database adapters. It will use sqlite by default.
#
<% if ENV['DATABASE_ADAPTER'] == 'postgres' %>
#
# Postgres
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= [Integer(ENV['RAILS_MAX_THREADS'] || 5), 5].max %>
development:
  <<: *default
  database: terrastories_development
test:
  <<: *default
  database: terrastories_test
# Use the DATABASE_URL environment variable when in production. This is simalar
# to how Heroku will reconfigure the database to connect to Postgres.
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

<% else %>

#
# sqlite
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000
development:
  <<: *default
  database: db/development.sqlite3
test:
  <<: *default
  database: db/test.sqlite3
production:
  <<: *default
  database: db/production.sqlite3

<% end %>

